/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GeoGebraPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/geogebra-renderer.ts
var import_obsidian2 = require("obsidian");

// src/geogebra-loader.ts
var import_obsidian = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  height: 640,
  width: "100%",
  appName: "classic",
  showToolBar: true,
  showAlgebraInput: true,
  showMenuBar: false,
  enableRightClick: true,
  enableShiftDragZoom: true,
  showResetIcon: true,
  attachmentFolder: "GeoGebra",
  deployScriptUrl: "https://www.geogebra.org/apps/deployggb.js",
  preferWikiEmbed: true
};
function stripWikiTarget(value) {
  return value.trim().replace(/^!/, "").replace(/^\[\[/, "").replace(/\]\]$/, "").split("|")[0].split("#")[0].trim();
}
function parseGeoGebraBlock(source) {
  const result = {};
  for (const rawLine of source.split("\n")) {
    const line = rawLine.replace(/^\uFEFF/, "").trim();
    if (!line || line.startsWith("#")) continue;
    const colon = line.indexOf(":");
    if (colon === -1) {
      if (!result.file && looksLikeGgbTarget(line)) {
        result.file = stripWikiTarget(line);
      }
      continue;
    }
    const key = line.slice(0, colon).trim().toLowerCase();
    const value = line.slice(colon + 1).trim();
    switch (key) {
      case "file":
      case "filename":
      case "path":
        result.file = stripWikiTarget(value);
        break;
      case "material":
      case "material_id":
      case "materialid":
        result.materialId = value;
        break;
      case "height":
        result.height = Number(value) || void 0;
        break;
      case "width":
        result.width = value === "100%" ? "100%" : Number(value) || value;
        break;
      case "app":
      case "appname":
        if (value === "classic" || value === "graphing" || value === "geometry" || value === "3d" || value === "suite") {
          result.appName = value;
        }
        break;
      case "toolbar":
      case "showtoolbar":
        result.showToolBar = value.toLowerCase() !== "false";
        break;
      case "algebra":
      case "showalgebrainput":
        result.showAlgebraInput = value.toLowerCase() !== "false";
        break;
      case "menu":
      case "showmenubar":
        result.showMenuBar = value.toLowerCase() !== "false";
        break;
    }
  }
  return result;
}
function looksLikeGgbTarget(line) {
  const target = stripWikiTarget(line);
  return /\.ggb$/i.test(target) || line.startsWith("[[") || line.startsWith("![[");
}

// src/geogebra-loader.ts
function resolveGgbFile(app, raw, sourcePath) {
  const name = stripWikiTarget(raw).replace(/\\/g, "/").replace(/^\.\//, "");
  if (!name) {
    throw new Error("\u672A\u6307\u5B9A .ggb \u6587\u4EF6");
  }
  const fromLink = app.metadataCache.getFirstLinkpathDest(name, sourcePath);
  if (fromLink instanceof import_obsidian.TFile) return fromLink;
  const byPath = app.vault.getAbstractFileByPath((0, import_obsidian.normalizePath)(name));
  if (byPath instanceof import_obsidian.TFile) return byPath;
  throw new Error(
    `\u627E\u4E0D\u5230\u6587\u4EF6: ${raw}\uFF08\u8BF7\u4F7F\u7528\u5E93\u5185\u5B8C\u6574\u8DEF\u5F84\uFF0C\u4F8B\u5982 GeoGebra/demo.ggb\uFF09`
  );
}
function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  const chunk = 32768;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}
function resolvedHeight(options) {
  return options.height ?? options.settings.height;
}
function parseHeightHint(el, fallback) {
  const attr = el.getAttribute("height") || el.getAttribute("alt") || el.getAttribute("width");
  if (!attr) return fallback;
  const match = attr.match(/(\d{2,4})/);
  if (!match) return fallback;
  const value = Number(match[1]);
  return Number.isFinite(value) && value > 80 ? value : fallback;
}
async function mountGeoGebraApplet(container, options, ctx) {
  if (!import_obsidian.Platform.isDesktopApp) {
    throw new Error(
      "\u4EA4\u4E92\u5F0F GeoGebra \u76EE\u524D\u4EC5\u652F\u6301\u684C\u9762\u7AEF\uFF08\u9700 Electron webview\uFF0C\u4E0E Excalidraw/Web Viewer \u76F8\u540C\uFF09\u3002"
    );
  }
  const adapter = ctx.plugin.app.vault.adapter;
  if (!(adapter instanceof import_obsidian.FileSystemAdapter)) {
    throw new Error("\u5F53\u524D vault \u4E0D\u662F\u672C\u5730\u6587\u4EF6\u7CFB\u7EDF\uFF0C\u65E0\u6CD5\u521B\u5EFA GeoGebra runtime\u3002");
  }
  const height = resolvedHeight(options);
  container.empty();
  container.addClass("geogebra-embed");
  if (options.fillContainer) {
    container.addClass("geogebra-embed-fill");
    container.removeClass("geogebra-embed-fixed");
    container.setCssProps({ "--geogebra-height": "100%" });
  } else {
    container.addClass("geogebra-embed-fixed");
    container.removeClass("geogebra-embed-fill");
    container.setCssProps({ "--geogebra-height": `${height}px` });
  }
  const status = container.createDiv({ cls: "geogebra-status geogebra-status-overlay" });
  status.setText("\u6B63\u5728\u52A0\u8F7D GeoGebra\u2026");
  const webview = createWebviewElement();
  if (!webview) {
    throw new Error(
      "\u5F53\u524D Obsidian \u672A\u542F\u7528 Electron webview\u3002\u8BF7\u4F7F\u7528\u684C\u9762\u7248 Obsidian\uFF08\u4E0E Excalidraw \u5916\u94FE\u5D4C\u5165\u76F8\u540C\u4F9D\u8D56\uFF09\u3002"
    );
  }
  webview.addClass("geogebra-webview");
  webview.setAttribute("allowpopups", "");
  webview.setAttribute(
    "webpreferences",
    "autoplayPolicy=document-user-activation-required"
  );
  container.appendChild(webview);
  await new Promise(
    (resolve) => window.requestAnimationFrame(
      () => window.requestAnimationFrame(() => resolve())
    )
  );
  const measure = () => {
    const w = Math.max(
      Math.floor(
        container.clientWidth || container.getBoundingClientRect().width
      ),
      320
    );
    const h = Math.max(
      Math.floor(
        container.clientHeight || container.getBoundingClientRect().height || height
      ),
      height
    );
    return { w, h };
  };
  const applyWebviewBox = (w, h) => {
    webview.setCssProps({
      "--geogebra-webview-width": `${w}px`,
      "--geogebra-webview-height": `${h}px`
    });
  };
  let { w: boxW, h: boxH } = measure();
  applyWebviewBox(boxW, boxH);
  const cleanups = [];
  let revoked = false;
  let webviewReady = false;
  const clearStatus = () => {
    if (status.isConnected) status.remove();
  };
  const syncSize = () => {
    if (revoked || !webview.isConnected) return;
    const { w, h } = measure();
    boxW = w;
    boxH = h;
    applyWebviewBox(w, h);
    if (!webviewReady || w < 2 || h < 2) return;
    void webview.executeJavaScript(
      `(function(){
  var w=${w}, h=${h};
  try {
    if (window.ggbApplet && typeof window.ggbApplet.setSize === "function") {
      window.ggbApplet.setSize(w, h);
    }
  } catch (e) {}
  try { window.dispatchEvent(new Event("resize")); } catch (e) {}
  return {w:w,h:h,iw:window.innerWidth,ih:window.innerHeight};
})()`,
      false
    ).catch(() => void 0);
  };
  const markReady = () => {
    webviewReady = true;
    clearStatus();
    syncSize();
    window.setTimeout(() => syncSize(), 300);
    window.setTimeout(() => syncSize(), 1e3);
  };
  const ro = new ResizeObserver(() => syncSize());
  ro.observe(container);
  cleanups.push(() => ro.disconnect());
  if (options.materialId && !options.ggbBase64) {
    webview.src = buildMaterialEmbedUrl(
      options.materialId,
      boxW,
      boxH,
      options
    );
    wireWebviewReady(webview, markReady, cleanups, () => revoked);
    return {
      el: webview,
      revoke: () => {
        revoked = true;
        runCleanups(cleanups);
        webview.remove();
      }
    };
  }
  const html = buildAppletHtml(options, boxW, boxH);
  const runtime = await writeRuntimeHtml(ctx.plugin, adapter, html);
  cleanups.push(runtime.cleanup);
  webview.src = runtime.fileUrl;
  wireWebviewReady(webview, markReady, cleanups, () => revoked);
  const safety = window.setTimeout(() => markReady(), 8e3);
  cleanups.push(() => window.clearTimeout(safety));
  return {
    el: webview,
    revoke: () => {
      revoked = true;
      runCleanups(cleanups);
      webview.remove();
    }
  };
}
function createWebviewElement() {
  const el = createEl("webview");
  if (el.tagName.toUpperCase() !== "WEBVIEW") {
    return null;
  }
  return el;
}
function wireWebviewReady(webview, onReady, cleanups, isRevoked) {
  let signaled = false;
  const markReady = () => {
    if (isRevoked() || signaled) return;
    signaled = true;
    onReady();
  };
  const onDomReady = () => {
    markReady();
  };
  webview.addEventListener("dom-ready", onDomReady);
  webview.addEventListener("did-finish-load", onDomReady);
  cleanups.push(() => {
    webview.removeEventListener("dom-ready", onDomReady);
    webview.removeEventListener("did-finish-load", onDomReady);
  });
}
function runCleanups(cleanups) {
  for (const fn of cleanups.splice(0)) {
    try {
      fn();
    } catch {
    }
  }
}
async function writeRuntimeHtml(plugin, adapter, html) {
  const pluginDirName = plugin.manifest.dir;
  if (!pluginDirName) {
    throw new Error("\u65E0\u6CD5\u89E3\u6790\u63D2\u4EF6\u76EE\u5F55\uFF08manifest.dir \u4E3A\u7A7A\uFF09");
  }
  const runtimeDir = (0, import_obsidian.normalizePath)(`${pluginDirName}/.runtime`);
  try {
    await adapter.mkdir(runtimeDir);
  } catch {
  }
  const fileName = `ggb-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.html`;
  const relativePath = (0, import_obsidian.normalizePath)(`${runtimeDir}/${fileName}`);
  await adapter.write(relativePath, html);
  try {
    const listed = await adapter.list(runtimeDir);
    const stale = listed.files.filter((name) => {
      const base = name.split("/").pop() ?? name;
      return base.startsWith("ggb-") && base.endsWith(".html");
    }).sort().reverse().slice(20);
    for (const path of stale) {
      try {
        await adapter.remove(path);
      } catch {
      }
    }
  } catch {
  }
  const absolutePath = adapter.getFullPath(relativePath);
  return {
    fileUrl: pathToFileUrl(absolutePath),
    cleanup: () => {
      void adapter.remove(relativePath).catch(() => void 0);
    }
  };
}
function pathToFileUrl(absolutePath) {
  const normalized = absolutePath.replace(/\\/g, "/");
  const prefixed = /^[A-Za-z]:\//.test(normalized) ? `/${normalized}` : normalized.startsWith("/") ? normalized : `/${normalized}`;
  return `file://${encodeURI(prefixed).replace(/#/g, "%23")}`;
}
function buildMaterialEmbedUrl(materialId, width, height, options) {
  const { settings } = options;
  const ai = options.showAlgebraInput ?? settings.showAlgebraInput ? "true" : "false";
  const stb = options.showToolBar ?? settings.showToolBar ? "true" : "false";
  const smb = options.showMenuBar ?? settings.showMenuBar ? "true" : "false";
  return `https://www.geogebra.org/material/iframe/id/${encodeURIComponent(materialId)}/width/${width}/height/${height}/border/888888/rc/${settings.enableRightClick}/ai/${ai}/sdz/${settings.enableShiftDragZoom}/smb/${smb}/stb/${stb}/stbh/false/ld/false/sri/${settings.showResetIcon}`;
}
function buildAppletHtml(options, width, height) {
  const { settings } = options;
  const params = {
    appName: options.appName ?? settings.appName,
    width,
    height,
    showToolBar: options.showToolBar ?? settings.showToolBar,
    showAlgebraInput: options.showAlgebraInput ?? settings.showAlgebraInput,
    showMenuBar: options.showMenuBar ?? settings.showMenuBar,
    enableRightClick: settings.enableRightClick,
    enableShiftDragZoom: settings.enableShiftDragZoom,
    showResetIcon: settings.showResetIcon,
    language: "zh",
    preventFocus: false,
    borderColor: null,
    autoHeight: false
  };
  if (options.ggbBase64) {
    params.ggbBase64 = options.ggbBase64;
  }
  if (options.materialId) {
    params.material_id = options.materialId;
  }
  const scriptUrl = JSON.stringify(settings.deployScriptUrl);
  const paramsJson = JSON.stringify(params);
  const fallbackW = JSON.stringify(width);
  const fallbackH = JSON.stringify(height);
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>GeoGebra</title>
<style>
  html, body {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
    background: #fff;
  }
  #ggb-host, #ggb {
    width: 100%;
    height: 100%;
    box-sizing: border-box;
  }
</style>
<script src=${scriptUrl}><\/script>
</head>
<body>
<div id="ggb-host">
  <div id="ggb"></div>
</div>
<script>
(function () {
  function fail(msg) {
    document.body.textContent = msg;
    document.body.style.padding = "16px";
    document.body.style.fontFamily = "sans-serif";
    document.body.style.color = "#b00020";
  }
  function hostSize() {
    var host = document.getElementById("ggb-host");
    var w = host ? host.clientWidth : 0;
    var h = host ? host.clientHeight : 0;
    return {
      w: Math.max(Math.floor(w || window.innerWidth || ${fallbackW}), 100),
      h: Math.max(Math.floor(h || window.innerHeight || ${fallbackH}), 100)
    };
  }
  function applySize(api) {
    var s = hostSize();
    try {
      if (api && typeof api.setSize === "function") api.setSize(s.w, s.h);
      else if (window.ggbApplet && typeof window.ggbApplet.setSize === "function") {
        window.ggbApplet.setSize(s.w, s.h);
      }
    } catch (e) {}
  }
  try {
    var params = ${paramsJson};
    var initial = hostSize();
    params.width = Math.max(initial.w, ${fallbackW});
    params.height = Math.max(initial.h, ${fallbackH});
    params.appletOnLoad = function (api) {
      applySize(api);
      document.documentElement.setAttribute("data-ggb-ready", "1");
    };
    if (typeof GGBApplet !== "function") {
      fail("\u65E0\u6CD5\u52A0\u8F7D GeoGebra \u5F15\u64CE\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u662F\u5426\u80FD\u8BBF\u95EE geogebra.org");
      return;
    }
    var applet = new GGBApplet(params, true);
    applet.inject("ggb");
    window.addEventListener("resize", function () { applySize(window.ggbApplet); });
    if (typeof ResizeObserver === "function") {
      var ro = new ResizeObserver(function () { applySize(window.ggbApplet); });
      var host = document.getElementById("ggb-host");
      if (host) ro.observe(host);
    }
  } catch (err) {
    fail(String(err && err.message ? err.message : err));
  }
})();
<\/script>
</body>
</html>`;
}

// src/geogebra-renderer.ts
var GeoGebraRenderChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(containerEl, plugin, sourcePath, config, file) {
    super(containerEl);
    this.mounted = null;
    this.generation = 0;
    this.plugin = plugin;
    this.sourcePath = sourcePath;
    this.config = config;
    this.file = file;
  }
  /** Obsidian embed registry calls this instead of onload(). */
  async loadFile(file) {
    if (file instanceof import_obsidian2.TFile) {
      this.file = file;
    }
    await this.render();
  }
  onload() {
    void this.render();
  }
  onunload() {
    this.generation += 1;
    this.mounted?.revoke();
    this.mounted = null;
  }
  async render() {
    const token = ++this.generation;
    this.mounted?.revoke();
    this.mounted = null;
    this.containerEl.empty();
    this.containerEl.addClass("geogebra-embed");
    this.containerEl.addClass("geogebra-embed-fixed");
    const height = parseHeightHint(
      this.containerEl,
      resolvedHeight({
        height: this.config.height,
        settings: this.plugin.settings
      })
    );
    this.containerEl.setCssProps({ "--geogebra-height": `${height}px` });
    const status = this.containerEl.createDiv({ cls: "geogebra-status" });
    status.setText("\u6B63\u5728\u52A0\u8F7D GeoGebra\u2026");
    try {
      const file = this.file ?? this.resolveFile();
      let ggbBase64;
      const materialId = this.config.materialId;
      if (file) {
        this.file = file;
        const data = await this.plugin.app.vault.readBinary(file);
        if (token !== this.generation) return;
        ggbBase64 = arrayBufferToBase64(data);
      } else if (!materialId) {
        throw new Error("\u672A\u6307\u5B9A .ggb \u6587\u4EF6\u6216 material_id");
      }
      if (token !== this.generation) return;
      this.mounted = await mountGeoGebraApplet(
        this.containerEl,
        {
          settings: this.plugin.settings,
          height,
          width: this.config.width,
          appName: this.config.appName,
          showToolBar: this.config.showToolBar,
          showAlgebraInput: this.config.showAlgebraInput,
          showMenuBar: this.config.showMenuBar,
          ggbBase64,
          materialId
        },
        { plugin: this.plugin }
      );
      if (token !== this.generation) {
        this.mounted.revoke();
        this.mounted = null;
      }
    } catch (error) {
      if (token !== this.generation) return;
      const message = error instanceof Error ? error.message : String(error);
      status.setText(message);
      status.addClass("geogebra-status-error");
      new import_obsidian2.Notice(`GeoGebra: ${message}`);
    }
  }
  resolveFile() {
    if (this.config.file) {
      return resolveGgbFile(
        this.plugin.app,
        this.config.file,
        this.sourcePath
      );
    }
    return null;
  }
};

// src/geogebra-view.ts
var import_obsidian3 = require("obsidian");
var GEOGEBRA_VIEW_TYPE = "geogebra-view";
var GeoGebraView = class extends import_obsidian3.FileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.mounted = null;
    this.plugin = plugin;
  }
  getViewType() {
    return GEOGEBRA_VIEW_TYPE;
  }
  getDisplayText() {
    return this.file?.basename ?? "GeoGebra";
  }
  getIcon() {
    return "pyramid";
  }
  async onLoadFile(file) {
    this.mounted?.revoke();
    this.mounted = null;
    this.contentEl.empty();
    this.contentEl.addClass("geogebra-file-view");
    const status = this.contentEl.createDiv({ cls: "geogebra-status" });
    status.setText("\u6B63\u5728\u52A0\u8F7D GeoGebra\u2026");
    const host = this.contentEl.createDiv({ cls: "geogebra-embed" });
    try {
      const data = await this.plugin.app.vault.readBinary(file);
      this.mounted = await mountGeoGebraApplet(
        host,
        {
          settings: this.plugin.settings,
          ggbBase64: arrayBufferToBase64(data),
          fillContainer: true
        },
        { plugin: this.plugin }
      );
      status.remove();
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      status.setText(message);
      status.addClass("geogebra-status-error");
    }
  }
  async onUnloadFile() {
    this.mounted?.revoke();
    this.mounted = null;
    this.contentEl.empty();
  }
};

// src/settings-tab.ts
var import_obsidian4 = require("obsidian");
var APP_NAME_OPTIONS = {
  classic: "Classic",
  graphing: "Graphing",
  geometry: "Geometry",
  "3d": "3D Calculator",
  suite: "Calculator Suite"
};
var GeoGebraSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Obsidian 1.13+: searchable declarative settings (skips display when non-empty). */
  getSettingDefinitions() {
    return [
      {
        name: "Default height",
        desc: "Applet height in pixels",
        control: {
          type: "number",
          key: "height",
          min: 1,
          placeholder: "500",
          defaultValue: DEFAULT_SETTINGS.height
        }
      },
      {
        name: "App type",
        desc: "Default GeoGebra app when opening .ggb files",
        control: {
          type: "dropdown",
          key: "appName",
          options: APP_NAME_OPTIONS,
          defaultValue: DEFAULT_SETTINGS.appName
        }
      },
      {
        name: "Show toolbar",
        control: { type: "toggle", key: "showToolBar" }
      },
      {
        name: "Show algebra input",
        control: { type: "toggle", key: "showAlgebraInput" }
      },
      {
        name: "Show menu bar",
        control: { type: "toggle", key: "showMenuBar" }
      },
      {
        name: "Enable right-click",
        control: { type: "toggle", key: "enableRightClick" }
      },
      {
        name: "Enable shift-drag zoom",
        control: { type: "toggle", key: "enableShiftDragZoom" }
      },
      {
        name: "Show reset icon",
        control: { type: "toggle", key: "showResetIcon" }
      },
      {
        name: "Attachment folder",
        desc: "Vault-relative folder used when dropping external .ggb files",
        control: {
          type: "text",
          key: "attachmentFolder",
          placeholder: "GeoGebra",
          defaultValue: DEFAULT_SETTINGS.attachmentFolder
        }
      },
      {
        name: "Prefer wiki embed on drop",
        desc: "Insert ![[file.ggb]] instead of a geogebra code block",
        control: { type: "toggle", key: "preferWikiEmbed" }
      },
      {
        name: "deployggb.js URL",
        desc: "CDN or self-hosted GeoGebra loader script",
        control: {
          type: "text",
          key: "deployScriptUrl",
          placeholder: DEFAULT_SETTINGS.deployScriptUrl,
          defaultValue: DEFAULT_SETTINGS.deployScriptUrl
        }
      }
    ];
  }
  async setControlValue(key, value) {
    if (key === "attachmentFolder") {
      this.plugin.settings.attachmentFolder = String(value ?? "").trim() || DEFAULT_SETTINGS.attachmentFolder;
      await this.plugin.saveSettings();
      return;
    }
    if (key === "deployScriptUrl") {
      this.plugin.settings.deployScriptUrl = String(value ?? "").trim() || DEFAULT_SETTINGS.deployScriptUrl;
      await this.plugin.saveSettings();
      return;
    }
    if ((0, import_obsidian4.requireApiVersion)("1.13.0")) {
      await super.setControlValue(key, value);
    }
  }
  /** Fallback for Obsidian before 1.13.0 */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Default height").setDesc("Applet height in pixels").addText(
      (text) => text.setPlaceholder("500").setValue(String(this.plugin.settings.height)).onChange(async (value) => {
        const n = Number(value);
        if (Number.isFinite(n) && n > 0) {
          this.plugin.settings.height = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian4.Setting(containerEl).setName("App type").setDesc("Default GeoGebra app when opening .ggb files").addDropdown((dropdown) => {
      dropdown.addOptions(APP_NAME_OPTIONS);
      dropdown.setValue(this.plugin.settings.appName);
      dropdown.onChange(async (value) => {
        this.plugin.settings.appName = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Show toolbar").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showToolBar).onChange(async (value) => {
        this.plugin.settings.showToolBar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show algebra input").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showAlgebraInput).onChange(async (value) => {
        this.plugin.settings.showAlgebraInput = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show menu bar").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showMenuBar).onChange(async (value) => {
        this.plugin.settings.showMenuBar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Enable right-click").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableRightClick).onChange(async (value) => {
        this.plugin.settings.enableRightClick = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Enable shift-drag zoom").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableShiftDragZoom).onChange(async (value) => {
        this.plugin.settings.enableShiftDragZoom = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show reset icon").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showResetIcon).onChange(async (value) => {
        this.plugin.settings.showResetIcon = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Attachment folder").setDesc("Vault-relative folder used when dropping external .ggb files").addText(
      (text) => text.setPlaceholder("GeoGebra").setValue(this.plugin.settings.attachmentFolder).onChange(async (value) => {
        this.plugin.settings.attachmentFolder = value.trim() || DEFAULT_SETTINGS.attachmentFolder;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Prefer wiki embed on drop").setDesc("Insert ![[file.ggb]] instead of a geogebra code block").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.preferWikiEmbed).onChange(async (value) => {
        this.plugin.settings.preferWikiEmbed = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("deployggb.js URL").setDesc("CDN or self-hosted GeoGebra loader script").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.deployScriptUrl).setValue(this.plugin.settings.deployScriptUrl).onChange(async (value) => {
        this.plugin.settings.deployScriptUrl = value.trim() || DEFAULT_SETTINGS.deployScriptUrl;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var GeoGebraPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      GEOGEBRA_VIEW_TYPE,
      (leaf) => new GeoGebraView(leaf, this)
    );
    this.registerExtensions(["ggb"], GEOGEBRA_VIEW_TYPE);
    this.registerMarkdownCodeBlockProcessor(
      "geogebra",
      (source, el, ctx) => this.mountCodeBlock(source, el, ctx)
    );
    this.registerMarkdownCodeBlockProcessor(
      "ggb",
      (source, el, ctx) => this.mountCodeBlock(source, el, ctx)
    );
    this.registerWikiEmbed();
    this.registerReadingFallback();
    this.registerEvent(
      this.app.workspace.on("editor-drop", (evt, editor, info) => {
        if (evt.defaultPrevented) return;
        if (!this.eventHasGgb(evt)) return;
        evt.preventDefault();
        if (this.settings.preferWikiEmbed) {
          void this.insertWikiEmbedsFromEvent(evt, editor, info);
          return;
        }
        void this.insertCodeBlocksFromEvent(evt, editor, info);
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-paste", (evt, editor, info) => {
        if (evt.defaultPrevented) return;
        if (!this.eventHasGgb(evt)) return;
        evt.preventDefault();
        if (this.settings.preferWikiEmbed) {
          void this.insertWikiEmbedsFromEvent(evt, editor, info);
          return;
        }
        void this.insertCodeBlocksFromEvent(evt, editor, info);
      })
    );
    this.addCommand({
      id: "insert-code-block",
      name: "Insert code block",
      editorCallback: (editor) => {
        const snippet = [
          "```ggb",
          "path/to/file.ggb",
          "```",
          ""
        ].join("\n");
        editor.replaceSelection(snippet);
      }
    });
    this.addSettingTab(new GeoGebraSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  mountCodeBlock(source, el, ctx) {
    const config = parseGeoGebraBlock(source);
    ctx.addChild(new GeoGebraRenderChild(el, this, ctx.sourcePath, config));
  }
  registerWikiEmbed() {
    const embedRegistry = this.app.embedRegistry;
    if (!embedRegistry?.registerExtension) return;
    try {
      if (embedRegistry.isExtensionRegistered?.("ggb")) {
        embedRegistry.unregisterExtension?.("ggb");
      }
    } catch {
    }
    try {
      embedRegistry.unregisterExtension?.("ggb");
    } catch {
    }
    embedRegistry.registerExtension("ggb", (ctx, file) => {
      return new GeoGebraRenderChild(
        ctx.containerEl,
        this,
        ctx.sourcePath ?? file.path,
        { file: file.path },
        file
      );
    });
    this.register(() => {
      try {
        embedRegistry.unregisterExtension?.("ggb");
      } catch {
      }
    });
  }
  registerReadingFallback() {
    this.registerMarkdownPostProcessor((el, ctx) => {
      const embeds = el.querySelectorAll("span.internal-embed");
      for (const span of Array.from(embeds)) {
        if (!span.instanceOf(HTMLElement)) continue;
        if (span.querySelector(".geogebra-webview, .geogebra-status")) continue;
        const src = (span.getAttribute("src") ?? "").split("|")[0].trim();
        if (!src.toLowerCase().endsWith(".ggb")) continue;
        const file = this.app.metadataCache.getFirstLinkpathDest(
          src,
          ctx.sourcePath
        );
        if (!(file instanceof import_obsidian5.TFile)) continue;
        ctx.addChild(
          new GeoGebraRenderChild(
            span,
            this,
            ctx.sourcePath,
            { file: file.path },
            file
          )
        );
      }
    });
  }
  eventHasGgb(evt) {
    if (this.externalGgbFiles(evt).length > 0) return true;
    if (this.vaultGgbFiles(evt).length > 0) return true;
    if (evt instanceof DragEvent) {
      return this.extractInternalGgbPaths(evt).length > 0;
    }
    return false;
  }
  async collectGgbPathsFromEvent(evt, sourcePath) {
    const paths = [];
    if (evt instanceof DragEvent) {
      paths.push(...this.extractInternalGgbPaths(evt));
    }
    for (const file of this.vaultGgbFiles(evt)) {
      paths.push(file.path);
    }
    for (const file of this.externalGgbFiles(evt)) {
      try {
        paths.push(await this.importGgbFile(file, sourcePath));
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        new import_obsidian5.Notice(`GeoGebra: ${message}`);
      }
    }
    return [...new Set(paths)];
  }
  linktextForPath(path, sourcePath) {
    const file = this.app.vault.getAbstractFileByPath((0, import_obsidian5.normalizePath)(path));
    if (file instanceof import_obsidian5.TFile) {
      return this.app.metadataCache.fileToLinktext(file, sourcePath);
    }
    return path;
  }
  async insertWikiEmbedsFromEvent(evt, editor, info) {
    const sourcePath = info instanceof import_obsidian5.MarkdownView ? info.file?.path ?? "" : info.file?.path ?? "";
    const paths = await this.collectGgbPathsFromEvent(evt, sourcePath);
    if (paths.length === 0) {
      new import_obsidian5.Notice("GeoGebra: \u672A\u627E\u5230\u53EF\u63D2\u5165\u7684 .ggb \u6587\u4EF6");
      return;
    }
    const snippet = paths.map((path) => `![[${this.linktextForPath(path, sourcePath)}]]`).join("\n");
    editor.replaceSelection(snippet.endsWith("\n") ? snippet : `${snippet}
`);
  }
  async insertCodeBlocksFromEvent(evt, editor, info) {
    const sourcePath = info instanceof import_obsidian5.MarkdownView ? info.file?.path ?? "" : info.file?.path ?? "";
    const paths = await this.collectGgbPathsFromEvent(evt, sourcePath);
    for (const path of paths) {
      editor.replaceSelection(["```ggb", path, "```", ""].join("\n"));
    }
  }
  externalGgbFiles(evt) {
    const list = evt instanceof DragEvent ? evt.dataTransfer?.files : evt.clipboardData?.files;
    if (!list) return [];
    return Array.from(list).filter(
      (file) => file.name.toLowerCase().endsWith(".ggb")
    );
  }
  vaultGgbFiles(_evt) {
    const draggable = this.app.dragManager?.draggable;
    if (!draggable) return [];
    const files = [];
    if (draggable.file instanceof import_obsidian5.TFile) files.push(draggable.file);
    if (Array.isArray(draggable.files)) {
      for (const file of draggable.files) {
        if (file instanceof import_obsidian5.TFile) files.push(file);
      }
    }
    return files.filter((file) => file.extension.toLowerCase() === "ggb");
  }
  extractInternalGgbPaths(evt) {
    const dt = evt.dataTransfer;
    if (!dt) return [];
    const candidates = [];
    for (const type of ["text/plain", "Text", "text/uri-list"]) {
      const raw = dt.getData(type);
      if (raw) candidates.push(raw);
    }
    const paths = [];
    for (const raw of candidates) {
      for (const line of raw.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        const wiki = trimmed.match(/!?\[\[([^\]]+)\]\]/);
        const path = (wiki?.[1] ?? trimmed).split("|")[0].split("#")[0].trim();
        if (!path.toLowerCase().endsWith(".ggb")) continue;
        const file = this.app.vault.getAbstractFileByPath((0, import_obsidian5.normalizePath)(path)) ?? this.app.metadataCache.getFirstLinkpathDest(path, "");
        if (file instanceof import_obsidian5.TFile) paths.push(file.path);
      }
    }
    return [...new Set(paths)];
  }
  async importGgbFile(file, _sourcePath) {
    const folder = await this.ensureAttachmentFolder();
    const uniqueName = await this.uniqueFileName(folder, file.name);
    const vaultPath = (0, import_obsidian5.normalizePath)(`${folder}/${uniqueName}`);
    const buffer = await file.arrayBuffer();
    await this.app.vault.createBinary(vaultPath, buffer);
    return vaultPath;
  }
  async ensureAttachmentFolder() {
    const configured = this.settings.attachmentFolder.trim() || "GeoGebra";
    const folder = (0, import_obsidian5.normalizePath)(configured);
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
    return folder;
  }
  async uniqueFileName(folder, originalName) {
    const safe = originalName.replace(/[\\/]/g, "-");
    let candidate = safe;
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(`${folder}/${candidate}`)) {
      const dot = safe.lastIndexOf(".");
      const base = dot === -1 ? safe : safe.slice(0, dot);
      const ext = dot === -1 ? "" : safe.slice(dot);
      candidate = `${base}-${i}${ext}`;
      i += 1;
    }
    return candidate;
  }
};
